/*

*************************************************************************

ArmageTron -- Just another Tron Lightcycle Game in 3D.
Copyright (C) 2000  Manuel Moos (manuel@moosnet.de)

**************************************************************************

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

***************************************************************************

*/

#include "rSDL.h"

#include "config.h"

#include "rTexture.h"
#include "rDisplayList.h"
#include "tString.h"
#include "rScreen.h"
#include "tDirectories.h"
#include "tLocale.h"
#include "tException.h"
#include "tResourceManager.h"

#include <sstream>

#ifndef DEDICATED
#include "rRender.h"
#include "rGL.h"

// Load the right SDL_IMAGE header

#ifdef _MSC_VER
#include <SDL_image.h>
#else
#ifdef __MINGW32__
#include <SDL_image.h>
#else
#ifdef HAVE_SDL_IMG_H
#include <SDL_image.h>
#else
#ifdef HAVE_SDL_SDL_IMAGE_H
#include <SDL/SDL_image.h>
#else
#ifdef HAVE_IMG_H
#include <IMG.h>
#else
#ifdef HAVE_SDL_IMG_H
#include <SDL/IMG.h>
#else
#ifdef HAVE_LIBSDL
#include <SDL_image.h>
#else
#ifdef HAVE_LIBIMG
#include <IMG.h>
#else
// if the following include ( or one of the earlier ones ) fails, you don't have SDL_image properly installed.
#include <SDL_image.h>
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif

// the ninth #endif above closed the #ifndef DEDICATED, so this needs its own
// guard: the dedicated build is compiled by Emscripten too, and has no GL at all
#if !defined( DEDICATED ) && defined( __EMSCRIPTEN__ )
// glGenerateMipmap replaces gluBuild2DMipmaps in Upload() below. Nothing extra
// has to be included for it: it arrives through rGL.h -> <SDL_opengl.h> ->
// emsdk's <GL/gl.h>, whose tail (gl.h:2085-2093) includes <GL/glext.h>
// unconditionally unless GL_GLEXT_LEGACY is defined, and that macro appears
// nowhere in src/ or web/. rGL.h's NO_SDL_GLEXT does not interfere -- it
// suppresses SDL's own bundled copy of glext, whose guard would have been
// __glext_h_, whereas emsdk's real header guards on __gl_glext_h_
// (glext.h:1-2). Emscripten implements the function as a passthrough to
// WebGLRenderingContext.generateMipmap (src/lib/libwebgl.js, generated by
// createGLPassthroughFunctions from the glPassthroughFuncs table).

//! true when the surface rISurfaceTexture::Upload last uploaded was not
//! power-of-two, and so has no mip chain; read by OnSelect a few lines after it
//! calls Upload. See the comment at the assignment for why a file static is
//! sound here.
static bool sr_uploadWasNPOT = false;
#endif


// ******************************************************************************************
// *
// *	rSurface
// *
// ******************************************************************************************
//!
//!		@param	fileName	name of the file to load sufrace from
//!
// ******************************************************************************************

rSurface::rSurface( char const * fileName )
{
    Init();
    Create( fileName );
}

// ******************************************************************************************
// *
// *	~rSurface
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rSurface::~rSurface( void )
{
    Clear();
}

// ******************************************************************************************
// *
// *	rSurface
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rSurface::rSurface( void )
{
    Init();
}

// ******************************************************************************************
// *
// *   rSurface
// *
// ******************************************************************************************
//!
//!        @param  other   source to copy from
//!
// ******************************************************************************************

rSurface::rSurface( rSurface const & other )
{
    Init();
    CopyFrom( other );
}

// ******************************************************************************************
// *
// *   operator =
// *
// ******************************************************************************************
//!
//!        @param  other
//!        @return
//!
// ******************************************************************************************

rSurface & rSurface::operator =( rSurface const & other )
{
    if ( &other != this )
    {
        Clear();
        CopyFrom( other );
    }

    return *this;
}

// ******************************************************************************************
// *
// *	Init
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rSurface::Init( void )
{
    surface_ = 0;
    format_ = 0;
}

// ******************************************************************************************
// *
// *   Clear
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rSurface::Clear( void )
{
#ifndef DEDICATED
    // delete surface
    if ( surface_ )
        SDL_FreeSurface( surface_ );

#endif
    surface_ = 0;
}

// ******************************************************************************************
// *
// *	Create
// *
// ******************************************************************************************
//!
//!		@param	fileName	name of the image file to load
//!
// ******************************************************************************************

void rSurface::Create( char const * fileName )
{
#ifndef DEDICATED
    sr_LockSDL();

    // find path of image
    // tString s = tResourceManager::locateResource("", fileName);
    tString s = tDirectories::Data().GetReadPath( fileName );

    // Load image
#ifdef __EMSCRIPTEN__
    // Emscripten's SDL/SDL_image.h declares IMG_InvertAlpha() but nothing
    // implements it, so the call is an undefined symbol at link time. That same
    // header (SDL_image.h:88-89) says of it: "This function is now a no-op, and
    // only provided for backwards compatibility." So dropping the call should
    // change nothing. If that turns out to be wrong the symptom is unmistakable
    // and global: every texture renders with its alpha channel inverted.
#else
    IMG_InvertAlpha(true);
#endif
    Create( IMG_Load(s) );

    //if ( surface_ )
    //    std::cerr << "loaded surface " << fileName << "\n";

    sr_UnlockSDL();
#endif
}

// ******************************************************************************************
// *
// *	Create
// *
// ******************************************************************************************
//!
//!		@param	surface
//!
// ******************************************************************************************

void rSurface::Create( SDL_Surface * surface )
{
#ifndef DEDICATED
    // clear previous surface
    Clear();

    // take ownership
    surface_ = surface;

    // determine texture format
    if ( surface_ )
    {
        switch (surface_->format->BytesPerPixel){
        case 1:
            format_ = GL_LUMINANCE;
            break;

        case 2:
#ifdef __EMSCRIPTEN__
            // format_ is handed to glTexImage2D's *external format* argument
            // (see rISurfaceTexture::Upload), and GL_LUMINANCE8_ALPHA8 is a
            // sized *internal* format. Desktop GL tolerated the confusion;
            // WebGL 1 accepts only GL_ALPHA/GL_LUMINANCE/GL_LUMINANCE_ALPHA/
            // GL_RGB/GL_RGBA there and rejects anything else with
            // GL_INVALID_ENUM. Emscripten's glTexImage2D would also size the
            // pixel read from it wrongly: libwebgl.js's
            // colorChannelsInGlTextureFormat falls back to 1 byte per pixel for
            // an unrecognised enum, so it would hand WebGL a half-length
            // buffer. This branch is unreachable in the Emscripten build --
            // SDL's IMG_Load_RW always returns a 32-bit surface, so
            // BytesPerPixel is always 4 -- but it costs one line to be right.
            format_ = GL_LUMINANCE_ALPHA;
#else
            format_ = GL_LUMINANCE8_ALPHA8;
#endif
            break;

        case 3:
            format_ = GL_RGB;
            break;

        case 4:
            format_ = GL_RGBA;
            break;

        default:
            {
                // fallback: convert the texture into a known format.

                SDL_Surface *dummy =
                    SDL_CreateRGBSurface(SDL_SWSURFACE, 1, 1,
                                         32,
                                         0x0000FF, 0x00FF00,
                                         0xFF0000 ,0xFF000000);

                SDL_Surface *convtex =
                    SDL_ConvertSurface(surface_, dummy->format, SDL_SWSURFACE);

                SDL_FreeSurface(surface_);
                surface_ = convtex;
                SDL_FreeSurface(dummy);

                format_ = GL_RGBA;
            }
            break;
        }
    }
#endif
}

// ******************************************************************************************
// *
// *	CopyFrom
// *
// ******************************************************************************************
//!
//!		@param	other
//!
// ******************************************************************************************

void rSurface::CopyFrom( rSurface const & other )
{
#ifndef DEDICATED
    tASSERT( 0 == surface_ );
    tASSERT( other.surface_ );

    // copy surface
    surface_ = SDL_ConvertSurface(other.surface_, other.surface_->format, SDL_SWSURFACE);

    // copy flags
    format_ = other.format_;
#endif
}

// ******************************************************************************************
// *
// *	~rITexture
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rITexture::~rITexture( void )
{
    s_textures_.Remove(this,id_);
}

// ******************************************************************************************
// *
// *	UnloadAll
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rITexture::UnloadAll( void )
{
    for(int i=s_textures_.Len()-1;i>=0;i--)
    {
        s_textures_(i)->Unload();
    }
}

// ******************************************************************************************
// *
// *	LoadAll
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rITexture::LoadAll( void )
{
    // s_reportErrors=false;
    for(int i=s_textures_.Len()-1;i>=0;i--)
    {
        s_textures_(i)->Select();
        //if (i>=s_textures.Len())
        //    i=s_textures.Len()-1;
    }
    // s_reportErrors=true;
}

// ******************************************************************************************
// *
// *	rITexture
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rITexture::rITexture( void )
        : id_( -1 )
{
}

// ******************************************************************************************
// *
// *	OnSelect
// *
// ******************************************************************************************
//!
//!		@param	enforce enforce when set to true, the texture should be loaded even if the configuration says it should not
//!
// ******************************************************************************************

void rITexture::OnSelect( bool enforce )
{
    if ( id_ < 0 )
        s_textures_.Add(this,id_);
}

// ******************************************************************************************
// *
// *	OnUnload
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rITexture::OnUnload( void )
{
}

// ******************************************************************************************
// *
// *	rISurfaceTexture
// *
// ******************************************************************************************
//!
//!		@param	group	texture group ( floor/wall)
//!		@param	repx    flag indicating the x repeat mode
//!		@param	repy    flag indicating the y repeat mode
//!		@param	storeAlpha flag indicating whether the alpha channel should be stored
//!
// ******************************************************************************************

rISurfaceTexture::rISurfaceTexture( int group, bool repx, bool repy, bool storeAlpha )
        : group_( group ), textureModeLast_( -1), tint_( 0 ), repx_( repx ), repy_( repy ), storeAlpha_( storeAlpha )
{
}

// ******************************************************************************************
// *
// *	~rISurfaceTexture
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rISurfaceTexture::~rISurfaceTexture( void )
{
#ifndef DEDICATED
    if (tint_ > 0)
    {
        rDisplayList::ClearAll();

        glDeleteTextures(1,&tint_);
        tint_ = 0;
    }
#endif
}

// ******************************************************************************************
// *
// *	ProcessImage
// *
// ******************************************************************************************
//!
//!		@param	surface the surface to process
//!
// ******************************************************************************************

void rISurfaceTexture::ProcessImage( SDL_Surface * surface )
{
}

// ******************************************************************************************
// *
// *	Upload
// *
// ******************************************************************************************
//!
//!		@param	surface
//!
// ******************************************************************************************

void rISurfaceTexture::Upload( rSurface & surface )
{
#ifndef DEDICATED
#ifndef GL_CLAMP_TO_EDGE
// GL_CLAMP_TO_EDGE was observed undefined in Windows; should be the same as GL_CLAMP.
#define GL_CLAMP_TO_EDGE GL_CLAMP
#endif

    sr_LockSDL();
    GLenum texformat = surface.GetFormat();
    SDL_Surface * tex = surface.GetSurface();
    tASSERT( tex );

    bool texalpha=tex->format->Amask;

    ProcessImage(tex);

    if(repx_)
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_REPEAT);
    else
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);
    if(repy_)
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_REPEAT);
    else
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);

    int format;
    if (sr_texturesTruecolor)
        if (storageHack_ || ( storeAlpha_ && texalpha ) )
            format=GL_RGBA8;
        else
            format=GL_RGB8;
    else
        if (storageHack_ || ( storeAlpha_ && texalpha ) )
            format=GL_RGBA4;
        else
            format=GL_RGB5;

#ifdef __EMSCRIPTEN__
    // Emscripten declares gluBuild2DMipmaps but does not implement it. Plain
    // glTexImage2D is the replacement, but GLU silently did three further
    // things that have to be done by hand, and each of them renders every
    // texture solid black if it is missed.

    // (1) SIZED INTERNAL FORMATS. `format` above is always one of GL_RGBA8,
    //     GL_RGB8, GL_RGBA4 or GL_RGB5 -- all *sized*. WebGL 1 accepts only the
    //     unsized set for internalformat, and additionally requires
    //     internalformat == format. So the only value that can ever be legal
    //     here is texformat itself, which makes the invariant hold by
    //     construction for every value rSurface::Create can put in format_
    //     (GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_RGB, GL_RGBA -- all four are in
    //     WebGL 1's unsized set).
    //
    //     What that discards is the two things `format` also encoded: "store at
    //     16 bits" (GL_RGBA4/GL_RGB5) and "drop the alpha channel"
    //     (GL_RGB8/GL_RGB5). WebGL 1 can express neither without rewriting the
    //     pixel data. The first is a memory/precision tradeoff for 2003 cards
    //     and is no loss. The second is a behaviour change in principle --
    //     alpha the game meant to discard is kept, so a texture could blend
    //     where it used to be opaque -- but it is unobservable for every
    //     texture this game *ships*. Of the shipped ones uploaded without
    //     StoreAlpha, textures/floor.png, textures/floor_b.png (gFloor.cpp) and
    //     textures/rim_wall.png (eAdvWall.cpp) have no alpha channel at all,
    //     textures/floor_a.png's is uniformly 255, and cycle_body.png /
    //     cycle_wheel.png are forced to alpha 255 by
    //     gTextureCycle::ProcessImage (gCycle.cpp:272) in the ProcessImage call
    //     a few lines above. Everything with real transparency -- the three
    //     fonts, sky.png, shadow.png, dir_wall.png, title.jpg -- asks for alpha
    //     and gets it.
    //
    //     The residual exposure is moviepack slots, which ship empty and take
    //     user-supplied files: moviepack/floor.png (gFloor.cpp:93) and
    //     moviepack/rim_wall_a..d.png (gWall.cpp:88-91) are the storeAlpha=false
    //     ones. A partly transparent file dropped into any of those would blend
    //     where the desktop build made it opaque. That is a documented
    //     limitation, not a regression here. Moviepack *cycle* skins are not
    //     exposed: gCycle.cpp's LoadTextureSafe2 builds both the "textures" and
    //     the "moviepack" path and hands either to gTextureCycle
    //     (gCycle.cpp:2091), so ProcessImage flattens the alpha either way.
    (void)format;
    GLenum const internalFormat = texformat;

    // (2) NON-POWER-OF-TWO RESCALING. GLU scaled NPOT sources up to the nearest
    //     power of two before uploading. WebGL 1 refuses NPOT textures twice
    //     over: with GL_REPEAT wrap (set just above) and with a mipmapped
    //     minification filter. Either makes the texture incomplete, and an
    //     incomplete texture samples as solid black.
    //
    //     Only one shipped texture is NPOT: textures/title.jpg at 800x600. It
    //     is loaded (gLogo.cpp:150) into rTextureGroups::TEX_FONT with
    //     repx=repy=0, so the wrap half is settled -- it clamps already. The
    //     mipmap half is NOT settled by configuration, and this is the part
    //     that is easy to get wrong: rScreen.cpp:810-811 does clamp TEX_FONT
    //     down to GL_LINEAR ("fonts look best in bilinear filtering, no
    //     mipmaps"), but it does not have the last word. rScreen.cpp:1003 puts
    //     GL_NEAREST_MIPMAP_NEAREST back on TEX_FONT in sr_LoadDefaultConfig's
    //     software-renderer branch, which lowlevel_sr_InitDisplay calls at :827
    //     -- *after* the clamp -- and TEXTURE_MODE_3 is an ordinary tConfItem
    //     (gMenus.cpp:53) settable from the console long after screen-mode init,
    //     which is the only place the clamp runs. So title.jpg can be handed a
    //     mipmapped min filter, and the demotion in OnSelect is what stops that
    //     from turning it black. That demotion is load-bearing, not
    //     belt-and-braces; do not delete it as dead code.
    //
    //     Given that, no resampler is needed for the content this build ships,
    //     and inventing a resampling filter for a case that does not occur
    //     would be the riskier change. What is here instead is a degradation
    //     rather than an assert: an NPOT texture loses its mip chain and is
    //     forced to clamp. That costs quality at distance and tiles wrongly if
    //     it was meant to repeat, but it stays visible, and it never takes the
    //     title screen down the way an assert would.
    //
    //     One caveat on "stays visible": rFont::OnSelect (rFont.cpp:142) re-sets
    //     GL_TEXTURE_WRAP_S to GL_REPEAT after rISurfaceTexture::OnSelect
    //     returns, i.e. after the clamp below. An NPOT font would therefore get
    //     the illegal NPOT+GL_REPEAT combination back and render solid black
    //     with no diagnostic. That cannot happen today -- font.png and
    //     font_extra.png are 256x256 and font_s.png is 128x128 -- but a
    //     non-power-of-two replacement font would need that line guarded too.
    bool const potWidth  = tex->w > 0 && ( tex->w & ( tex->w  - 1 ) ) == 0;
    bool const potHeight = tex->h > 0 && ( tex->h & ( tex->h  - 1 ) ) == 0;
    bool const powerOfTwo = potWidth && potHeight;

    if ( !powerOfTwo )
    {
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);
        glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);
    }

    glTexImage2D( GL_TEXTURE_2D, 0, internalFormat, tex->w, tex->h, 0,
                  texformat, GL_UNSIGNED_BYTE, tex->pixels );

    // (3) THE MIP CHAIN. rTextureGroups::TextureMode defaults to
    //     GL_LINEAR_MIPMAP_LINEAR for three of its four groups, and OnSelect
    //     applies it to GL_TEXTURE_MIN_FILTER *after* this function returns. A
    //     texture with a mipmapped min filter and no mip chain is incomplete in
    //     WebGL 1, i.e. solid black, so the chain has to exist for every
    //     texture that could get such a filter. This sits on the straight-line
    //     path right after the game's only glTexImage2D, with no early return
    //     between the two, so no successful upload can reach that filter
    //     without it. The one case it does not cover is NPOT, handled below.
    if ( powerOfTwo )
    {
        glGenerateMipmap( GL_TEXTURE_2D );
    }

    // glGenerateMipmap raises GL_INVALID_OPERATION on an NPOT texture and
    // builds nothing, so an NPOT texture must not be given a mipmapped min
    // filter either. OnSelect sets that filter after this returns and would
    // overwrite anything set here, so hand the fact over to it. A file static
    // is enough: OnSelect calls Upload (via the virtual OnSelect()) and then
    // sets the filter a few lines later in the same call, with no rendering in
    // between, and this code is only ever reached from the render thread.
    sr_uploadWasNPOT = !powerOfTwo;
#else
    gluBuild2DMipmaps(GL_TEXTURE_2D,format,tex->w,tex->h,
                      texformat,GL_UNSIGNED_BYTE,tex->pixels);
#endif

    sr_UnlockSDL();
 #endif
}

// ******************************************************************************************
// *
// *	OnSelect
// *
// ******************************************************************************************
//!
//!		@param	enforce enforce when set to true, the texture should be loaded even if the configuration says it should not
//!
// ******************************************************************************************

void rISurfaceTexture::OnSelect( bool enforce )
{
#ifndef DEDICATED
    if(sr_glOut)
    {
        RenderEnd(true);

        int texmod=rTextureGroups::TextureMode[group_];
        if (enforce && texmod<0) texmod=GL_NEAREST_MIPMAP_NEAREST;

        if(textureModeLast_!=texmod)
        {
            // unload texture if the mode changed
            if ( tint_ > 0 )
                Unload();
            tASSERT( tint_ == 0 );
            // std::cerr << "loading texture " << fileName << ':' << tint << "\n";

            if (texmod>0){
                // don't generate textures inside display lists
                rDisplayList::Cancel();

                glGenTextures(1, &tint_);
                glBindTexture(GL_TEXTURE_2D,tint_);

                if (textureModeLast_<0)
                {
#ifdef __EMSCRIPTEN__
                    // cleared here rather than trusted from last time, so a
                    // derived OnSelect() that uploads nothing (rSurfaceTexture
                    // with a null surface) cannot leave a stale answer behind
                    sr_uploadWasNPOT = false;
#endif
                    // delegate core loading work to derived class
                    OnSelect();
                }

                //glEnable(GL_TEXTURE);
                glEnable(GL_TEXTURE_2D);

#ifdef __EMSCRIPTEN__
                // WebGL 1 has no mip chain for a non-power-of-two texture --
                // Upload() cannot build one, glGenerateMipmap rejects the
                // target -- and a mipmapped min filter over a missing chain is
                // an incomplete texture, which samples as solid black. Demote
                // to the matching non-mipmapped filter. Nothing the game ships
                // reaches this on the ordinary path -- but it is reachable, so
                // treat it as load-bearing rather than belt-and-braces. TEX_FONT
                // is not pinned to GL_LINEAR the way rScreen.cpp:810-811 makes
                // it look. Two routes get past that clamp and would hand the
                // game's one NPOT texture, textures/title.jpg, a mipmapped min
                // filter: rScreen.cpp:1003 restores GL_NEAREST_MIPMAP_NEAREST on
                // TEX_FONT in sr_LoadDefaultConfig's software-renderer branch,
                // called from lowlevel_sr_InitDisplay at :827 -- after the clamp
                // -- and TEXTURE_MODE_3 (gMenus.cpp:53) is a plain tConfItem
                // that can be set from the console at any later point, while the
                // clamp only runs at screen-mode init. The enforce path twenty
                // lines above is a third route to a mipmapped filter for NPOT
                // textures generally, though not for title.jpg, which gLogo.cpp
                // selects without enforce. Whether any of these fires in a
                // browser is untested; the point is that none of them is closed.
                //
                // texmod itself must stay untouched: it is what textureModeLast_
                // is compared against on the next Select, so demoting it would
                // make every frame see a changed mode and unload/reupload the
                // texture. Only the value handed to GL_TEXTURE_MIN_FILTER moves.
                // The GL_TEXTURE_MAG_FILTER switch below is left on texmod for
                // the same reason it always was: magnification never samples a
                // mip level, so a missing chain does not concern it.
                int minFilter = texmod;
                if ( sr_uploadWasNPOT )
                {
                    switch( minFilter )
                    {
                    case GL_NEAREST_MIPMAP_NEAREST:
                    case GL_NEAREST_MIPMAP_LINEAR:
                        minFilter = GL_NEAREST;
                        break;
                    case GL_LINEAR_MIPMAP_NEAREST:
                    case GL_LINEAR_MIPMAP_LINEAR:
                        minFilter = GL_LINEAR;
                        break;
                    default:
                        break;
                    }
                }

                glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,
                                minFilter);
#else
                glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,
                                texmod);
#endif

                switch(texmod)
                {
                case GL_NEAREST:
                case GL_NEAREST_MIPMAP_NEAREST:
                    glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,
                                    GL_NEAREST);
                    break;
                default:
                    glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,
                                    GL_LINEAR);
                    break;
                }

            }
            else
            {
                glDisable(GL_TEXTURE_2D);
            }
        }
        else
        {
            glBindTexture(GL_TEXTURE_2D,tint_);
            if (texmod>0)
            {
                glEnable(GL_TEXTURE_2D);
            }
            else
            {
                glDisable(GL_TEXTURE_2D);
            }
        }
        textureModeLast_=texmod;
    }
    rITexture::OnSelect(enforce);
#endif
}

// ******************************************************************************************
// *
// * OnSelect
// *
// ******************************************************************************************
//!
//!  In derived classes, this routine is supposed to do the work of loading the texture
//!  into memory and using the Upload() function to upload it to OpenGL.
//!
// ******************************************************************************************

void rISurfaceTexture::OnSelect()
{
}

// ******************************************************************************************
// *
// *	OnUnload
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rISurfaceTexture::OnUnload( void )
{
#ifndef DEDICATED
    if (tint_ > 0)
    {
        rDisplayList::ClearAll();

        // std::cerr << "unloading texture " << fileName << ':' << tint_ << "\n";
        glDeleteTextures(1,&tint_);
        tint_ = 0;
    }

    textureModeLast_=-100;
    rITexture::OnUnload();
#endif
}

// ******************************************************************************************
// *
// *	StoreAlpha
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rISurfaceTexture::StoreAlpha( void )
{
    storeAlpha_ = true;
}

// ******************************************************************************************
// *
// *	rFileTexture
// *
// ******************************************************************************************
//!
//!		@param	group	texture group ( floor/wall)
//!		@param	fileName the filename of the picture to load
//!		@param	repx    flag indicating the x repeat mode
//!		@param	repy    flag indicating the y repeat mode
//!		@param	storeAlpha flag indicating whether the alpha channel should be stored
//!
// ******************************************************************************************

rFileTexture::rFileTexture( int group, char const * fileName, bool repx, bool repy, bool storeAlpha )
        : rISurfaceTexture( group, repx, repy, storeAlpha )
        ,  fileName_( fileName )
{
}

// ******************************************************************************************
// *
// *	~rFileTexture
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rFileTexture::~rFileTexture( void )
{
}

// ******************************************************************************************
// *
// *	OnSelect
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rFileTexture::OnSelect()
{
#ifndef DEDICATED
    // std::cerr << "loading texture " << fileName_ << "\n";
    rSurface surface( fileName_ );
    if ( surface.GetSurface() )
    {
        this->Upload( surface );
    }
    else if (s_reportErrors_)
    {
        throw tGenericException( tOutput( "$texture_error_filenotfound", fileName_ ), tOutput("$texture_error_filenotfound_title") );
    }
    rISurfaceTexture::OnSelect();
#endif
}

// ******************************************************************************************
// *
// *	rSurfaceTexture
// *
// ******************************************************************************************
//!
//!		@param	group	texture group ( floor/wall)
//!		@param	surface
//!		@param	repx    flag indicating the x repeat mode
//!		@param	repy    flag indicating the y repeat mode
//!		@param	storeAlpha flag indicating whether the alpha channel should be stored
//!
// ******************************************************************************************

rSurfaceTexture::rSurfaceTexture( int group, rSurface const & surface, bool repx, bool repy, bool storeAlpha )
        : rISurfaceTexture( group, repx, repy, storeAlpha )
        , surface_( surface )
{
}

// ******************************************************************************************
// *
// *	~rSurfaceTexture
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

rSurfaceTexture::~rSurfaceTexture( void )
{
}

// ******************************************************************************************
// *
// *	OnSelect
// *
// ******************************************************************************************
//!
//!
// ******************************************************************************************

void rSurfaceTexture::OnSelect()
{
#ifndef DEDICATED
    // upload a copy of the surface ( it may get modified )
    if ( surface_.GetSurface() )
    {
        rSurface copy( surface_ );
        this->Upload( copy );
        rISurfaceTexture::OnSelect();
    }
#endif
}


bool rISurfaceTexture::s_reportErrors_=false;
tList<rITexture> rITexture::s_textures_;

int rTextureGroups::TextureMode[rTextureGroups::TEX_GROUPS]
#ifndef DEDICATED
={GL_LINEAR_MIPMAP_LINEAR, GL_LINEAR_MIPMAP_LINEAR, GL_LINEAR_MIPMAP_LINEAR, GL_LINEAR }
#endif
;

char const * rTextureGroups::TextureGroupDescription[rTextureGroups::TEX_GROUPS]=
    {
        "$texture_mode_0_help",
        "$texture_mode_1_help",
        "$texture_mode_2_help",
        "$texture_mode_3_help",
    };

bool rISurfaceTexture::storageHack_ = false;

//rTexture ArmageTron_eWall("wWall.png",1,0);
//rTexture ArmageTron_dir_eWall("wall.png",1,0);


static rCallbackBeforeScreenModeChange unload(&rITexture::UnloadAll);

// static rCallbackAfterScreenModeChange load(&rITexture::LoadAll);
