/* Natively, this header is generated by the version machinery, which stamps the
   exact source revision into TRUE_ARMAGETRONAD_VERSION.

   THIS FILE IS CURRENTLY INERT — nothing in the wasm build includes it. Both
   files that reference it wrap the #include in `#ifdef TOP_SOURCE_DIR`
   (src/network/nNetwork.cpp:96-98, src/render/rConsoleCout.cpp:56-58), and this
   port deliberately never defines TOP_SOURCE_DIR — natively it comes from
   configure.ac:907, and src/emscripten/config.h leaves it out on purpose.
   Both files then fall back to `#define TRUE_ARMAGETRONAD_VERSION VERSION`
   (nNetwork.cpp:100-102, rConsoleCout.cpp:60-62), which is exactly what this
   file would have supplied. Deleting it would change nothing today.

   It is kept for parity with the native generated-header layout, and because
   activating it is a one-line change: define TOP_SOURCE_DIR in
   src/emscripten/config.h and both includes fire, at which point this file has
   to already exist on the include path. Give it a real revision string here if
   that day comes. */
#ifndef TRUE_ARMAGETRONAD_VERSION
#define TRUE_ARMAGETRONAD_VERSION VERSION
#endif
